locale:
  no_permission: "&cYou should have permission!"
  wrong_usage: "&7Wrong usage, type &c/<0> help" # <0> used command
  commands:
    makoto:
      help: |
        &c<0> help &7- show this message
        &c<0> reload &7- reload config
        &c<0> badwords add/remove <word> &7- allows you to edit badwords from config
      reload: "&7Makotochat config reloaded"
      badwords:
        add: "&c<0> &7added"
        remove: "&c<0> &7removed"

chat:
  useCustomName: true
  hasGlobalChat: true
  system_msg:
      death:
        enabled: false
        causes:
          contact: "<0> was pricked to death"
          entity_attack: "<0> was slain by <1>"
          entity_sweep_attack: "<0> was killed by <1>  "
          projectile: "<0> was shot by <1>"
          suffocation: "<0> suffocated in a wall"
          fall: "<0> hit the ground too hard"
          fire: "<0> went up in flames"
          fire_tick: "<0> burned to death"
          melting: "<0> was melted"
          lava: "<0> tried to swim in lava"
          drowning: "<0> drowned"
          block_explosion: "<0> blew up"
          entity_explosion: "<0> went off with a bang"
          void: "<0> fell out of the world"
          lightning: "<0> was struck by lightning"
          suicide: "<0> suicided"
          starvation: "<0> starved to death"
          poison: "<0> was poisoned"
          magic: "<0> was killed by magic"
          wither: "<0> withered away"
          falling_block: "<0> was squashed"
          thorns: "<0> was killed trying to hurt <1>"
          dragon_breath: "<0> was killed by Ender Dragon using magic"
          custom: "<0> died"
          fly_into_wall: "<0> experienced kinetic energy"
          hot_floor: "<0> discovered the floor was lava"
          cramming: "<0> was squished too much"
          dryout: "<0> withered away"
          freeze: "<0> froze to death"
          sonic_boom: "<0> was slain by Warden!"

      player_join:
        enabled: false
        messages: #can be used many messages
          - " &l&7+ &r&7<0>"
          #- "&l&7-> &r&7Player <0> joined the server!"
          #- "&7Hello, <0>!"
      player_exit:
        enabled: false
        messages:
          - " &l&7- &r&7<0>"
          #- "&l&7<- &r&7Player <0> left the server!"
          #- "&7Bye, <0>!"
  mentions:
    enabled: true
    prefix: "" #can be "@", ex.: Hi, @MotyaRolla
    format: "&6@<0>&r" # if prefix equals "" Hi, &6@MotyaRolla&r
    alarm:
      enabled: true
      sound: "ENTITY_PLAYER_LEVELUP"
      message: "&c<0> &7tagged you!" #<1> - who was tagged; <0> - who tagged;
  automod:
    enabled: false
    blur: #blur word if the word is in a badwords
      enabled: true
      good_words: ["kitty","cat","frog"]
      format: "&o<0>&r" #<0> - word from list above. Ex. "he looks like (badword)!" -> "he looks like &o(goodword)&r!"
      alarm:
        enabled: true
        sound: "BLOCK_ANVIL_FALL"
        message: "&cAH! &7<0> replaced to <1>!" #<0> - bad word; <1> - new word;
    discord_alarms:
      #need to create webhook on log channel (only for mods)
      #if chat message only contains badword
      enabled: false
      webhook: "webhook"
      embed:
        title: "Warning!"
        description: "<0>: <1>" # <0> - player nickname, <1> - full message with bold badword
        footer: "found: <0>" #<0> - bad word
badwords: ["bad", "word"]