name: MakotoChat
version: '${project.version}'
main: ru.makotomc.makotochat.MakotoChat
api-version: 1.15
authors: [ MotyaRolla, Makotomc ]
description: Provides modern chat features for your server!
website: makotomc.ru
permissions:
  makotochat.admin:
    description: Admin permission
commands:
  makotochat:
    description: Main plugin command
  makotomsg:
    description: Command for sending private messages
    aliases: ["reply", "r","re","m","msg","ms","pm","w"]
